# Generated by Django 5.2.12 on 2026-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('cafe', 'Кафе'), ('restaurant', 'Ресторан'), ('museum', 'Музей'), ('fast_food', 'Фастфуд'), ('bar', 'Бар'), ('supermarket', 'Супермаркет'), ('nightclub', 'Нічний клуб'), ('bakery', 'Пекарня'), ('theatre', 'Театр'), ('cinema', 'Кінотеатр'), ('park', 'Парк'), ('landmarks', 'Пам’ятки')], max_length=20),
        ),
    ]
