# Generated by Django 5.2.12 on 2026-06-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_open',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
