# Generated by Django 5.2.12 on 2026-05-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
