# Generated by Django 5.2.12 on 2026-06-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='has_start_location',
            field=models.BooleanField(default=False),
        ),
    ]
