# Generated by Django 5.2.12 on 2026-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_userroute_has_start_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='start_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userroute',
            name='start_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
