# Generated by Django 5.2.12 on 2026-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_userroute_start_lat_userroute_start_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroute',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
